# unMount default service account token in service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-qa
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-qa
  namespace: qa
automountServiceAccountToken: false